### PR TITLE
fix: `SgxLevelDB.Get()` should return a `nil` value if the key is not found

### LINKED ISSUE #65: `SgxLevelDB.Get()` should return a `nil` value if the key is not found
Because `SgxLevelDB` implements the interface [tmdb.DB](https://github.com/tendermint/tm-db/blob/b599fa5d668d5a68812ec5ebeccb9eb05235bb3a/types.go#L21), it should conform to the spec of `tmdb.DB` completely.

The `tmdb.DB.Get()` should return a `nil` value if the key is not found. 
https://github.com/tendermint/tm-db/blob/b599fa5d668d5a68812ec5ebeccb9eb05235bb3a/types.go#L22
The `tmdb.GoLevelDB.Get()` (which implements `tmdb.DB`) was also implement like that.
https://github.com/tendermint/tm-db/blob/b599fa5d668d5a68812ec5ebeccb9eb05235bb3a/goleveldb.go#L50

This issue is slightly related to the issue https://github.com/medibloc/panacea-doracle/issues/62.

### PR DESCRIPTION
**Pull request by youngjoon-lee**
Closes #65

### CODE REVIEW

**Review by gyuguen — APPROVED** [review]
LGTM 👍

**Review by audtlr24 — APPROVED** [review]
lgtm!

**Review by 0xHansLee — APPROVED** [review]
👍

**Review by inchori — APPROVED** [review]
lgtm

**Pull request merged**
